import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '../components/Navbar'
import { Footer } from '../components/Footer'
import { Content } from '@/components/Content'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Coada la prună',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/plum16x16.ico" type="image/x-icon" />
                <link rel="icon" href="/plum16x16.png" type="image/png" />
                <link rel="icon" href="/plum16x16.svg" type="image/svg+xml" />
            </head>
            <body className={(inter.className, 'flex min-h-screen flex-col')}>
                <Navbar />
                <Content>{children}</Content>
                <Footer />
            </body>
        </html>
    )
}

// test
